#' Plot KDE of Relative Transcript Positions
#'
#' This function creates a KDE (kernel density estimate) plot of transcript
#' positions across 5' UTR, CDS, and 3' UTR regions based on precomputed
#' relative position values.
#'
#' @param df A data frame containing the columns `rel_5utr`, `rel_cds`, and
#'   `rel_3utr`, which represent the relative positions of sites in the 5' UTR,
#'   CDS, and 3' UTR regions, respectively. These columns are typically
#'   generated by a preceding function `map_relative_tx_regions_to_m6a`.
#' @param label A character string used as the label or title suffix for the
#'   plot.
#'
#' @return A `ggplot` object showing the density distribution of transcriptomic
#'   sites across regions.
#' @importFrom  ggplot2 ggplot geom_density geom_vline annotate arrow
#'   scale_x_continuous scale_y_continuous theme_minimal labs theme
#'   element_blank
#' @importFrom  dplyr tibble
#' @importFrom  grid unit
#' @export
#' @examples
#' plot <- plot_rel_positions(m6A_rel_tx_regions, "Sample A")
#' ggsave("m6a_tx_regions_for_SampleA.pdf", plot)

plot_relative_positions <- function(df, label = "") {
  # Combine relative positions
  rel_positions <- c(
    df$rel_5utr[df$rel_5utr > 0],
    df$rel_cds[df$rel_cds > 0] + 1,
    df$rel_3utr[df$rel_3utr > 0] + 2
  )

  # Create data frame for plotting
  plot_df <- dplyr::tibble(rel_position = rel_positions)

  # Create the KDE plot
  p <- ggplot2::ggplot(plot_df, ggplot2::aes(x = rel_position)) +
    ggplot2::geom_density(adjust = 0.5, fill = "blue", alpha=0.4, color = "black", linewidth = .75) +
    ggplot2::geom_vline(xintercept = 0, linetype = "dashed") +
    ggplot2::geom_vline(xintercept = 1, linetype = "dashed") +
    ggplot2::geom_vline(xintercept = 2, linetype = "dashed") +
    ggplot2::geom_vline(xintercept = 3, linetype = "dashed") +
    ggplot2::annotate("segment", x = 0, xend = 0.98, y = -0.02, yend = -0.02,
                      arrow = ggplot2::arrow(ends = "both", type = "closed", length = grid::unit(0.1, "inches")),
                      color = "black", linewidth = 1) +

    ggplot2::annotate("segment", x = 1.02, xend = 1.98, y = -0.02, yend = -0.02,
                      arrow = ggplot2::arrow(ends = "both", type = "closed", length = grid::unit(0.1, "inches")),
                      color = "black", linewidth = 1) +

    ggplot2::annotate("segment", x = 2.02, xend = 3, y = -0.02, yend = -0.02,
                      arrow = ggplot2::arrow(ends = "both", type = "closed", length = grid::unit(0.1, "inches")),
                      color = "black", linewidth = 1) +

    ggplot2::annotate("text", x = 0.5, y = -0.04, label = "5'UTR", size = 3.5, vjust = 1) +
    ggplot2::annotate("text", x = 1.5, y = -0.04, label = "CDS", size = 3.5, vjust = 1) +
    ggplot2::annotate("text", x = 2.5, y = -0.04, label = "3'UTR", size = 3.5, vjust = 1)+
    ggplot2::scale_x_continuous(limits = c(0, 3), breaks = NULL) +
    ggplot2::scale_y_continuous(limits = c(-.06, 2)) +
    ggplot2::theme_minimal() +
    ggplot2::labs(y = "Density", title = paste("Transcriptome-wide m6A Distribution for:", label)) +
    ggplot2::theme(
      axis.title.x = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_blank()
    )

  return(p)
}

